# -*- coding: utf-8 -*-
"""
Created on Fri Feb  5 11:50:40 2021

@author: Kai
"""

"""
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

What is the value of the first triangle number to have over five hundred 
divisors?
"""


"""creates list of triangle numbers and passes latest into seive funcion"""
def triang(num_div):
    i = 2
    trilist = [1]
    while i > 1:
        trilist.append(trilist[i-2] + i)
        ans = seive(trilist[-1])
        if ans > num_div:
            return(i, trilist[-1], ans)
        i +=1
        
    
"""
creates list of divisors of numbers passed to it, and returns the number of 
divisors"""
def seive(num):
    count = 2
    divisors = [1,num]
    stop_val = num/2
    while count <= stop_val:
        if num % count == 0:
            divisors.append(count)
        count += 1
    return(len(divisors))

print(triang(500))